FROM python:3.9-slim

WORKDIR /app

RUN pip install --no-cache-dir streamlit psycopg2-binary pandas plotly

COPY dashboard_ai.py .

EXPOSE 8501

CMD ["streamlit", "run", "dashboard_ai.py", "--server.port=8501", "--server.address=0.0.0.0", "--server.baseUrlPath=/ai-admin"]
